### PR TITLE
fix for recent nightlies' TestOpts change

### PR DESCRIPTION
**Pull request by cormacrelf**
See https://github.com/rust-lang/rust/pull/81356. The `filter: Option<String>` field was changed to `filters: Vec<String>`.

### CODE REVIEW

**Comment by cormacrelf** [comment]
Clippy failure wise... yeah, it will fail on stable. It's using unstable nightly APIs that are different between nightly and stable, it literally cannot pass clippy stable. The other two problems are fixed in the other PR.

**Comment by cormacrelf** [comment]
Ok, so a few updates:

- I made it compile on stable as well by using version_check.
- I think datatest is, by about rust 1.52, **_maybe going to stop working on stable._** See build.rs for a note on that.
- The last commit making test_case_registration the default is optional, I'm not sure if it is a breaking change or not. Probably not? The whole test suite passes with or without it. Maybe you didn't use it by default previously because that API might be a bit less stable than the ctor method. I've missed a bit but feel free to merge without it.

**Comment by mverleg** [comment]
Used this PR in my project and it solved the compile issue and runs the data-dependent tests successfully.

**Comment by cormacrelf** [comment]
I'll be sure to keep my main branch clean so that keeps working until this is merged.

**Comment by eranrund** [comment]
Hi! Any estimation on when this could get merged?
Thanks!

**Comment by mverleg** [comment]
Thanks for merging

**Pull request merged**
