### PR TITLE
Update datatest to work on 1.40

### PR DESCRIPTION
**Pull request by estebank**
Add new required field to `TestDesc`.

### CODE REVIEW

**Comment by idubrov** [comment]
Yeah, I have another PR open for it #19. I'm kind of holding it off since not sure if I want to merge it before tests pass on stable. But stable is not yet released, so maybe it's okay.

**Comment by estebank** [comment]
This will require latest version to support  <=1.38 and a new version for newer versions. I can put this behind a feature flag if you want.

CC https://github.com/commure/datatest/issues/18

**Comment by estebank** [comment]
This won't be needed until 1.40 (1.39 is fine), but I feel that the feature flag approach should be a reasonable imposition. What do you think? We could even peek the compiler version to enable the right feature so that it is seamless.

**Comment by cormacrelf** [comment]
2 notes:
* datatest is broken again on nightly as `rustc_test::parse_opts` has moved to `rustc_test::test::parse_opts`
* You probably want to replicate https://github.com/commure/datatest/pull/19/commits/e8db02024972c34efdf62c72177cca933c82d339 from #19

**Comment by idubrov** [comment]
Uh-oh. I'll take a look.

Yeah, I copied your changes from #19 to #21, but haven't merged them / finished (I tried used your branch initially, but messed up the merge).

**Comment by cormacrelf** [comment]
continue over at #19

**Pull request merged**
